// examples/vite-react/src/components/counter.tsx
import type { FC } from "react";
import { useState } from "react";

const Counter: FC = () => {
	const [count, setCount] = useState(0);

	return (
		// `flex` should be before height and width
		<div className="h-screen w-screen flex items-center justify-center flex-col gap-2">
			<p className="text-2xl font-medium">{`Count is ${count}`}</p>
			<button
				// `cursor-pointer` should be first
				className="bg-purple-700 text-white rounded-lg text-lg px-4 py-2 cursor-pointer"
				onClick={() => setCount(count => count + 1)}
			>
				Increment
			</button>
		</div>
	);
};

export default Counter;

// examples/vite-vue/src/components/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

const count = ref(0);
</script>

<template>
	<div class="flex h-full w-full flex-col items-center justify-center gap-2">
		<p class="text-2xl font-medium ">
			Count is {{ count }}
		</p>
		<button class="bg-purple-700 text-white rounded-lg text-lg px-4 py-2 cursor-pointer" type="button" @click="count++">
			Increment
		</button>
	</div>
</template>
